{
 "title": "Evidently Data Drift Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataset_name", "query": { "query": "label_values(dataset_name)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Evidently Data Drift Monitoring\n\n  This is a dashboard to visualise data drift. The dashboard queries data from Promethus and display them in this Grafana dashboard.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "General information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "Evidently:data_drift:dataset_drift{dataset_name=\"house_price_random_forest\"}",
     "legendFormat": "dataset drift"
    }
   ]
  },
  {
   "title": "Share of drifted features",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "Evidently:data_drift:share_drifted_features{dataset_name=\"house_price_random_forest\"}",
     "legendFormat": "share"
    }
   ]
  },
  {
   "title": "# of drifted features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Evidently:data_drift:n_drifted_features{dataset_name=\"house_price_random_forest\"}",
     "legendFormat": "Drifted"
    }
   ]
  },
  {
   "title": "# of features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Evidently:n_features{dataset_name=\"house_price_random_forest\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Detailed information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "P-value of features",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "Evidently:data_drift:p_value{dataset_name=\"house_price_random_forest\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "evidently:reference_dataset_hash",
     "legendFormat": "reference_hash"
    }
   ]
  }
 ]
}